name: NPM publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install --include-dev

      - name: Build package
        run: npm run compile

      - name: Publish to NPM
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
